version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "test_onesight"
    volumes:
      - .:/workspace:rw
    command: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
